
name: PR Verify

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: PR verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 6.0

      - name: Build with dotnet
        run: dotnet build --configuration Release
