
name: Secrets workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  secret:
    name: Secrets demo
    runs-on: ubuntu-latest

    steps:
      - name: echo secrets
        run: echo "the value of ${{ secret.TEST_SECRET }}"

